#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys


def main(argv):
    parser = argparse.ArgumentParser(description="pass-store credential helper")
    parser.add_argument("--full-host", action="store_true",
                        help="Send full host provided by git to pass")
    parser.add_argument("command")
    args = parser.parse_args(argv)

    # only support get, do not fail for any other command.
    if not args.command == 'get':
        raise SystemExit(0)

    pass_name = None

    for line in sys.stdin.readlines():
        try:
            key, value = line.split('=')
            if key == 'host':
                pass_name = value.strip()
                if not args.full_host:
                    pass_name = pass_name.split('.')[0]
        except ValueError:
            pass

    if pass_name is None:
        raise SystemExit("Could not determine host")
    elif not pass_name:
        raise SystemExit(0)  # no name, nothing to do

    try:
        output = subprocess.check_output(['pass', 'show', pass_name]).decode()
    except subprocess.CalledProcessError as e:
        raise SystemExit(e.returncode)

    pieces = output.split('\n')
    password = pieces[0]
    username = None
    if len(pieces) > 1:
        username = pieces[1].split(':')[1].strip()
    else:
        username = os.environ['USER']
    print("password={}\nusername={}".format(password, username))


if __name__ == '__main__':
    main(sys.argv[1:])
